
import { 
  FileImage, Crop, ArrowRight, Sparkles, Zap, 
  LayoutGrid, Maximize2, SlidersHorizontal, Pipette, Grid3X3, 
  ShieldAlert, Code2, ImageIcon, Palette, 
  Layers, Wind, Box, Split, Eye, 
  Type, Scaling, Ghost, Contrast, Aperture, Paintbrush2, Minimize2, 
  IterationCcw, Frame, Component, Focus, Sun, Filter,
  Music, TimerOff, Captions, Terminal, UserCircle,
  Hash, Binary, Search,
  Database, Activity,
  Wand2, Layers2, RefreshCcw, Flame, Coins,
  ImagePlus, Monitor,
  GlassWater, Camera, Cpu, Globe,
  Layout, Info, CheckCircle2, History, RotateCcw,
  Smartphone, Barcode, Key, FileJson, Link as LinkIcon, Ruler, Scan,
  MousePointer2, ShieldCheck, Lock, BrainCircuit,
  Settings2, Bot, Video, FileText, Languages, FileCode,
  Shield, Scale, Trash2, Scissors, ListChecks, FileType, 
  FileSpreadsheet, Clock, SearchCode, Braces, Table, AlignLeft,
  Waveform, Microscope, ScanEye, Brush, Waves, Volume2, 
  FileUp, Laptop, Globe2, Fingerprint, FileSearch, TerminalSquare,
  Network, Share2, MousePointerClick, MessageSquareText, PenTool,
  Sticker
} from 'lucide-react';

export interface Tool {
  title: string;
  description: string;
  href: string;
  icon: any;
  category: string;
  useCase: string;
}

export const ALL_TOOLS: Tool[] = [
  // AI Command Center (4)
  { title: 'AI Image Analyst', description: 'Analisis mendalam, alt-text, dan palet warna otomatis menggunakan Gemini 2.0.', href: '/ai-analyst', icon: BrainCircuit, category: 'ai', useCase: 'Smart' },
  { title: 'AI Background Gen', description: 'Hasilkan latar belakang artistik dari teks dengan model Imagen 4.', href: '/ai-background', icon: ImagePlus, category: 'ai', useCase: 'Creative' },
  { title: 'AI Audio Subtitle', description: 'Transkripsi otomatis suara menjadi file SRT dengan akurasi tinggi.', href: '/voice-to-srt', icon: Captions, category: 'ai', useCase: 'Sync' },
  { title: 'AI PDF Assistant', description: 'Ekstraksi data cerdas dan konversi dokumen PDF menggunakan AI.', href: '/pdf-converter', icon: Bot, category: 'ai', useCase: 'Automate' },

  // Berkas Core (8)
  { title: 'Konverter Gambar', description: 'Konversi massal ke WebP, JPG, PNG secara lokal dengan optimasi ukuran.', href: '/image-converter', icon: FileImage, category: 'core', useCase: 'Batch' },
  { title: 'Optimasi PNG', description: 'Kompresi aset PNG tanpa mengurangi kualitas (Lossless compression).', href: '/png-opt', icon: Minimize2, category: 'core', useCase: 'Size' },
  { title: 'Suite PDF', description: 'Transformasi PDF ke Word, Excel, atau PPT dengan tata letak yang rapi.', href: '/pdf-converter', icon: FileText, category: 'core', useCase: 'Doc' },
  { title: 'Atur DPI', description: 'Ubah resolusi cetak metadata gambar untuk kebutuhan percetakan.', href: '/dpi-adjuster', icon: Hash, category: 'core', useCase: 'Print' },
  { title: 'Hapus Metadata', description: 'Bersihkan data privasi EXIF dan GPS secara permanen dari foto.', href: '/metadata-cleaner', icon: ShieldAlert, category: 'core', useCase: 'Privacy' },
  { title: 'Base64 Tool', description: 'Ubah gambar menjadi string data URI untuk pengembangan web.', href: '/base64-tool', icon: Code2, category: 'core', useCase: 'Dev' },
  { title: 'Base64 Decoder', description: 'Ubah string Base64 kembali menjadi file media asli.', href: '/base64-decode', icon: Database, category: 'core', useCase: 'Extract' },
  { title: 'EXIF Inspector', description: 'Inspeksi data teknis dan properti tersembunyi pada biner gambar.', href: '/exif-view', icon: Scan, category: 'core', useCase: 'Analytic' },
  
  // Kreator & Layout (12)
  { title: 'Resizer Pro', description: 'Ubah ukuran gambar untuk preset Instagram, YouTube, dan Twitter.', href: '/resizer', icon: Maximize2, category: 'social', useCase: 'Resize' },
  { title: 'Grid Splitter', description: 'Potong gambar secara presisi untuk grid profil Instagram.', href: '/grid-splitter', icon: Grid3X3, category: 'social', useCase: 'IG Feed' },
  { title: 'Potong Cerdas', description: 'Hapus margin kosong atau transparan secara otomatis.', href: '/trim', icon: Crop, category: 'social', useCase: 'Clean' },
  { title: 'Image Stitcher', description: 'Gabungkan banyak gambar secara vertikal menjadi satu file.', href: '/stitcher', icon: Split, category: 'social', useCase: 'Layout' },
  { title: 'Generator Mockup', description: 'Presentasi produk dengan frame browser dan latar artistik.', icon: Monitor, href: '/mockup', category: 'social', useCase: 'Showcase' },
  { title: 'Avatar Bulat', description: 'Potong foto menjadi profil lingkaran sempurna untuk UI.', href: '/avatar-circle', icon: UserCircle, category: 'social', useCase: 'Profile' },
  { title: 'Corner Rounder', description: 'Bulatkan sudut gambar dengan radius piksel yang presisi.', href: '/corners', icon: Frame, category: 'social', useCase: 'UI/UX' },
  { title: 'Canvas Text', description: 'Tambah teks caption dan judul pada kanvas gambar.', href: '/canvas-text', icon: Type, category: 'social', useCase: 'Text' },
  { title: 'Watermark Pro', description: 'Tambah logo atau teks hak cipta untuk melindungi karya visual.', href: '/watermark', icon: Sticker, category: 'social', useCase: 'Copyright' },
  { title: 'Image Flipper', description: 'Putar balik gambar secara horisontal atau vertikal.', href: '/image-flipper', icon: RotateCcw, category: 'social', useCase: 'Mirror' },
  { title: 'Image Border', description: 'Tambahkan bingkai atau border warna pada foto Anda.', href: '/image-border', icon: Frame, category: 'social', useCase: 'Frame' },
  { title: 'Image to PDF', description: 'Ubah koleksi gambar Anda menjadi satu dokumen PDF.', href: '/image-to-pdf', icon: FileUp, category: 'social', useCase: 'Package' },

  // Studio FX - Artistic (17)
  { title: 'Filter Studio', description: 'Editor foto untuk kecerahan, kontras, dan suasana visual.', href: '/filters', icon: SlidersHorizontal, category: 'studio', useCase: 'Editor' },
  { title: 'Ekstrak Palet', description: 'Identifikasi warna dominan dan ambil kode HEX dari gambar.', href: '/palette-extractor', icon: Pipette, category: 'studio', useCase: 'Colors' },
  { title: 'Grayscale Pro', description: 'Konversi monokrom dengan kontrol kontras tinggi.', href: '/grayscale-pro', icon: ImageIcon, category: 'studio', useCase: 'B&W' },
  { title: 'Duotone Filter', description: 'Efek gradasi dua warna artistik untuk estetika modern.', href: '/duotone', icon: Sparkles, category: 'studio', useCase: 'Art' },
  { title: 'Vignette Studio', description: 'Efek gelap dramatis pada tepian gambar untuk fokus subjek.', href: '/vignette', icon: Aperture, category: 'studio', useCase: 'Drama' },
  { title: 'Posterize Art', description: 'Pengurangan level warna untuk gaya Pop Art yang unik.', href: '/posterize', icon: Paintbrush2, category: 'studio', useCase: 'Retro' },
  { title: 'Film Grain', description: 'Tekstur grain vintage sinematik untuk hasil foto analog.', href: '/film-grain', icon: Wind, category: 'studio', useCase: 'Analog' },
  { title: 'Glitch Maker', description: 'Efek distorsi digital bergaya cyberpunk yang estetik.', href: '/glitch', icon: IterationCcw, category: 'studio', useCase: 'Digital' },
  { title: 'ASCII Art Pro', description: 'Ubah gambar menjadi susunan karakter teks unik.', href: '/ascii-art', icon: Terminal, category: 'studio', useCase: 'Retro' },
  { title: 'Kaleidoscope', description: 'Ciptakan geometri fraktal melingkar dari gambar apa pun.', href: '/kaleido', icon: Focus, category: 'studio', useCase: 'Fractal' },
  { title: 'Pixelate Art', description: 'Ubah citra menjadi gaya retro 8-bit yang klasik.', href: '/pixelate', icon: Component, category: 'studio', useCase: 'Retro' },
  { title: 'Halftone Filter', description: 'Filter titik-titik koran retro untuk desain cetak.', href: '/halftone', icon: Binary, category: 'studio', useCase: 'Print' },
  { title: 'Oil Paint Art', description: 'Simulasi lukisan cat minyak tekstural secara digital.', href: '/oil-paint', icon: Brush, category: 'studio', useCase: 'Art' },
  { title: 'Pencil Sketch', description: 'Konversi foto menjadi sketsa arsir pensil yang artistik.', href: '/sketch', icon: Paintbrush2, category: 'studio', useCase: 'Draft' },
  { title: 'Solarize Filter', description: 'Efek artistik pembalikan warna berbasis ambang batas.', href: '/solarize', icon: Sparkles, category: 'studio', useCase: 'Creative' },
  { title: 'Bloom FX', description: 'Efek pendaran cahaya (glow) mewah untuk visual premium.', href: '/bloom', icon: Sun, category: 'studio', useCase: 'Beauty' },
  { title: 'Scan Line', description: 'Efek garis scan monitor CRT retro untuk video/foto.', href: '/scan-line', icon: Monitor, category: 'studio', useCase: 'CRT' },

  // Editor Teknis - Precision (20)
  { title: 'Sharpen Pro', description: 'Tingkatkan ketajaman garis tepi gambar secara lokal.', href: '/sharpen', icon: Wand2, category: 'advanced', useCase: 'Detail' },
  { title: 'Luminance Tool', description: 'Kontrol pencahayaan tingkat lanjut pada saluran luminansi.', href: '/luminance', icon: Sun, category: 'advanced', useCase: 'Lighting' },
  { title: 'Opacity Pro', description: 'Kontrol saluran alfa untuk transparansi gambar.', href: '/opacity', icon: Ghost, category: 'advanced', useCase: 'Alpha' },
  { title: 'Shadow Studio', description: 'Tambah kedalaman dengan drop shadow yang halus.', href: '/shadow-studio', icon: Layers, category: 'advanced', useCase: 'Depth' },
  { title: 'Threshold B&W', description: 'Konversi biner hitam putih murni berdasarkan level.', href: '/threshold', icon: Contrast, category: 'advanced', useCase: 'Binary' },
  { title: 'Color Balance', description: 'Keseimbangan warna RGB tingkat lanjut untuk grading.', href: '/color-balance', icon: Palette, category: 'advanced', useCase: 'Grading' },
  { title: 'Edge Detection', description: 'Analisis kontur garis tepi menggunakan kernel Laplacian.', href: '/edge-detection', icon: Wand2, category: 'advanced', useCase: 'Analytic' },
  { title: 'Loji Mixer', description: 'Pencampuran warna logaritma untuk tone unik.', href: '/loji-mix', icon: Camera, category: 'advanced', useCase: 'Tone' },
  { title: 'Color Mixer', description: 'Eksperimen pencampuran saluran warna RGB.', href: '/color-mixer', icon: Palette, category: 'advanced', useCase: 'Lab' },
  { title: 'Noise Studio', description: 'Generator tekstur grain analog fungsional.', href: '/noise', icon: Filter, category: 'advanced', useCase: 'Texture' },
  { title: 'Selective Gray', description: 'Isolasi warna tertentu dengan latar belakang abu-abu.', href: '/selective-gray', icon: MousePointer2, category: 'advanced', useCase: 'Focus' },
  { title: 'Gamma Tuner', description: 'Koreksi pencahayaan mid-tone tanpa merusak hitam/putih.', href: '/gamma', icon: Sun, category: 'advanced', useCase: 'Luma' },
  { title: 'Luma Keyer', description: 'Ekstraksi matte transparansi berdasarkan kecerahan.', href: '/luma-key', icon: Microscope, category: 'advanced', useCase: 'Matte' },
  { title: 'RGB Splitter', description: 'Pisahkan saluran warna primer Merah, Hijau, Biru.', href: '/rgb-split', icon: Split, category: 'advanced', useCase: 'Split' },
  { title: 'CMYK Splitter', description: 'Pisahkan kanal warna untuk kebutuhan separasi cetak.', href: '/cmyk-split', icon: Palette, category: 'advanced', useCase: 'Print' },
  { title: 'Histogram', description: 'Analisis distribusi tonal dan grafik warna citra.', href: '/histogram', icon: Activity, category: 'advanced', useCase: 'Analyze' },
  { title: 'Bulge Warp', description: 'Distorsi lensa cembung atau cekung pada gambar.', href: '/bulge', icon: Maximize2, category: 'advanced', useCase: 'Distort' },
  { title: 'Wave Distortion', description: 'Efek riak gelombang air dinamis pada gambar.', href: '/wave', icon: Waves, category: 'advanced', useCase: 'Liquid' },
  { title: 'Median Filter', description: 'Penghilang noise bintik (despeckle) tingkat lanjut.', href: '/median', icon: Filter, category: 'advanced', useCase: 'Denoise' },
  { title: 'Emboss Pro', description: 'Efek tekstur relief 3D pada elemen gambar.', href: '/emboss', icon: Layers, category: 'advanced', useCase: 'Relief' },

  // Studio Audio (4)
  { title: 'Audio FX Studio', description: 'Edit suara dengan 20+ profil studio musik profesional.', href: '/audio-cleaner', icon: Music, category: 'audio', useCase: 'Studio' },
  { title: 'Dead Air Remover', description: 'Hapus jeda sunyi pada podcast atau rekaman vokal.', href: '/dead-air-remover', icon: TimerOff, category: 'audio', useCase: 'Podcast' },
  { title: 'Subtitle Studio', description: 'Workstation editor subtitle manual dengan presisi tinggi.', href: '/voice-to-srt', icon: Captions, category: 'audio', useCase: 'Video' },
  { title: 'Text to Speech', description: 'Konversi teks menjadi suara vokal alami dengan AI.', href: '/tts', icon: Volume2, category: 'audio', useCase: 'Voice' },

  // Developer & Data Hub (35)
  { title: 'List Cleaner', description: 'Hapus duplikat dan sortir daftar teks secara massal.', href: '/list-cleaner', icon: ListChecks, category: 'dev', useCase: 'Text' },
  { title: 'Markdown Studio', description: 'Editor markdown real-time dengan pratinjau instan.', href: '/markdown-studio', icon: FileType, category: 'dev', useCase: 'Docs' },
  { title: 'JWT Inspector', description: 'Dekode dan periksa token JWT secara lokal dan aman.', href: '/jwt-inspector', icon: ShieldCheck, category: 'dev', useCase: 'Auth' },
  { title: 'HTML Entities', description: 'Enkode dan dekode karakter khusus entitas HTML.', href: '/html-entities', icon: Code2, category: 'dev', useCase: 'HTML' },
  { title: 'Flexbox Studio', description: 'Alat bantu visual desain tata letak CSS Flexbox.', href: '/flexbox-studio', icon: Layout, category: 'dev', useCase: 'CSS' },
  { title: 'CSS Grid Gen', description: 'Generator tata letak CSS Grid visual yang fungsional.', href: '/css-grid', icon: LayoutGrid, category: 'dev', useCase: 'Design' },
  { title: 'Glassmorphism', description: 'Generator efek UI kaca transparan (frosted glass).', href: '/glassmorphism', icon: GlassWater, category: 'dev', useCase: 'Design' },
  { title: 'Gradient Studio', description: 'Ciptakan gradasi warna linear CSS yang modern.', href: '/gradient-gen', icon: Palette, category: 'dev', useCase: 'Visual' },
  { title: 'JSON to YAML', description: 'Konversi format data JSON ke YAML secara instan.', href: '/json-yaml', icon: Braces, category: 'dev', useCase: 'Data' },
  { title: 'SQL Formatter', description: 'Rapikan dan beautify kode query database SQL.', href: '/sql-formatter', icon: Database, category: 'dev', useCase: 'SQL' },
  { title: 'RegEx Lab', description: 'Uji ekspresi reguler (RegEx) secara interaktif.', href: '/regex-lab', icon: SearchCode, category: 'dev', useCase: 'Logic' },
  { title: 'Color Contrast', description: 'Cek aksesibilitas kontras warna standar WCAG.', href: '/color-contrast', icon: Eye, category: 'dev', useCase: 'WCAG' },
  { title: 'CSV to JSON', description: 'Konversi data tabel CSV ke format objek JSON.', href: '/csv-json', icon: Table, category: 'dev', useCase: 'Convert' },
  { title: 'JSON Beautifier', description: 'Rapikan atau kompres kode JSON yang berantakan.', href: '/json-beautifier', icon: FileJson, category: 'dev', useCase: 'Code' },
  { title: 'Case Converter', description: 'Ubah teks ke UPPERCASE, lowercase, camelCase, snake_case.', href: '/case-converter', icon: Type, category: 'dev', useCase: 'Text' },
  { title: 'Hash Master', description: 'Generate hash SHA-256 secara biner dan lokal.', href: '/hash-master', icon: Lock, category: 'dev', useCase: 'Hash' },
  { title: 'URL Tool', description: 'Encode dan decode string URL dengan aman.', href: '/url-tool', icon: LinkIcon, category: 'dev', useCase: 'URL' },
  { title: 'PX to REM', description: 'Kalkulator konversi unit piksel ke REM untuk UI.', href: '/px-rem', icon: Ruler, category: 'dev', useCase: 'CSS' },
  { title: 'SVG Viewer', description: 'Inspeksi dan pratinjau kode sumber vektor SVG.', href: '/svg-view', icon: FileCode, category: 'dev', useCase: 'Vector' },
  { title: 'JS Obfuscator', description: 'Lindungi kode JavaScript Anda dengan obfuskasi lokal.', href: '/js-obfuscator', icon: TerminalSquare, category: 'dev', useCase: 'Security' },
  { title: 'Character Count', description: 'Hitung jumlah karakter, kata, dan spasi pada teks.', href: '/char-count', icon: AlignLeft, category: 'dev', useCase: 'Writer' },
  { title: 'Diff Checker', description: 'Bandingkan perbedaan baris antara dua teks.', href: '/diff-checker', icon: Split, category: 'dev', useCase: 'Review' },
  { title: 'Unit Converter', description: 'Konversi satuan berat, panjang, dan suhu umum.', href: '/unit-conv', icon: Network, category: 'dev', useCase: 'Math' },
  { title: 'Timezone Calc', description: 'Konversi waktu antar zona dunia secara akurat.', href: '/timezone', icon: Globe2, category: 'dev', useCase: 'Global' },
  { title: 'Color Wheel', description: 'Generator skema warna komplementer dan harmonis.', href: '/color-wheel', icon: Palette, category: 'dev', useCase: 'Artist' },
  { title: 'SVG Path Edit', description: 'Editor jalur vektor SVG sederhana berbasis koordinat.', href: '/svg-path', icon: PenTool, category: 'dev', useCase: 'Vector' },
  { title: 'JSON Schema', description: 'Hasilkan skema validasi dari data JSON Anda.', href: '/json-schema', icon: FileSearch, category: 'dev', useCase: 'Data' },
  { title: 'UA Parser', description: 'Analisis informasi browser dari string User Agent.', href: '/ua-parser', icon: Laptop, category: 'dev', useCase: 'Debug' },
  { title: 'Meta Tags Gen', description: 'Generator tag SEO lengkap untuk website Anda.', href: '/meta-tags', icon: Search, category: 'dev', useCase: 'SEO' },
  { title: 'QR Generator', description: 'Hasilkan kode QR statis untuk link atau kontak.', href: '/qr-gen', icon: Binary, category: 'utility', useCase: 'Scan' },
  { title: 'Barcode Maker', description: 'Buat barcode Code128 standar untuk label produk.', href: '/barcode-gen', icon: Barcode, category: 'utility', useCase: 'Retail' },
  { title: 'Password Pro', description: 'Generator kata sandi kuat berbasis entropi lokal.', href: '/password-gen', icon: Key, category: 'utility', useCase: 'Secure' },
  { title: 'Lorem Ipsum', description: 'Generator teks dummy placeholder untuk desain.', href: '/lorem-ipsum', icon: AlignLeft, category: 'utility', useCase: 'Draft' },
  { title: 'Aspect Ratio', description: 'Kalkulator proporsi dimensi gambar fungsional.', href: '/aspect-calculator', icon: Hash, category: 'utility', useCase: 'Math' },
  { title: 'Favicon Gen', description: 'Buat ikon browser (ICO) standar dari gambar.', href: '/favicon-generator', icon: Box, category: 'utility', useCase: 'Web' },
];
